services:
  - type: web
    name: sudarshan-api
    runtime: python
    rootDir: apps/api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn sudarshan.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./sudarshan.db
      - key: RAZORPAY_KEY_ID
        value: rzp_test_T2cBqTqXRpXgFk
      - key: RAZORPAY_KEY_SECRET
        value: ySj21N15sWEqqBuDG3Rhsm6e
      - key: PYTHON_VERSION
        value: 3.11.0
